name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
    paths-ignore:
    - 'build'
    - .git
      
jobs:
  Build_the_markup_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Install node dependencies
        run: npm ci
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install ruby dependencies
        run: bundle install
      - name: Build static site
        run: bundle exec middleman build  

  Deploy_the_markup_files:
    needs: Build_the_markup_files
    runs-on: ubuntu-latest
    steps:
       - name: make checkout folder for source
         run: |
             mkdir src && cd src   
             git clone https://github.com/P0C-demo/income-tax-mtd-end-to-end-service-guide.git
       - name: checkout destination
         run: |
             mkdir dest && cd dest
             git clone https://github.com/P0C-demo/P0C-demo.github.io.git   
       - name: copy and commit
         run: |         
             cp -r src/income-tax-mtd-end-to-end-service-guide/build/*  dest/P0C-demo.github.io/
       - name: Commit
         run: |
             cd dest/P0C-demo.github.io
             ls
             git config user.name "Github.Action"
             git config user.email "deliverablestangible@gmail.com"
             git add .
             git commit -m "Deploy to GitHub Pages"
             git push https://${{ secrets.PAT }}@github.com/P0C-demo/P0C-demo.github.io.git
